python -B train_S3DIS_pretrain.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-pre'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-pre' --last_path 'None' --weight 0 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-pre' --total_log '1pt'

python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration1' --load_dir '1pt-pre' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-pre/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration1' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-pre' --weight 1 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration1' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration2' --load_dir '1pt-iteration1' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration1/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration2' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration1' --weight 2 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration2' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration3' --load_dir '1pt-iteration2' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration2/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration3' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration2' --weight 3 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration3' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration4' --load_dir '1pt-iteration3' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration3/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration4' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration3' --weight 4 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration4' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration5' --load_dir '1pt-iteration4' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration4/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration5' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration4' --weight 5 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration5' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration6' --load_dir '1pt-iteration5' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration5/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration6' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration5' --weight 6 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration6' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration7' --load_dir '1pt-iteration6' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration6/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration7' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration6' --weight 7 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration7' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration8' --load_dir '1pt-iteration7' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration7/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration8' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration7' --weight 8 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration8' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration9' --load_dir '1pt-iteration8' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration8/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration9' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration8' --weight 9 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration9' --total_log '1pt'
python -B train_S3DIS_stage_2_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration10' --load_dir '1pt-iteration9' --pseudo_label_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration9/prediction/pseudo_label' --total_log '1pt' --gt_path './S3DIS_gt_2'
python -B main_S3DIS_pseudo_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration10' --last_path './experiment_mindspore/S3DIS/1_points_/1pt-iteration9' --weight 10 --total_log '1pt'
python -B main_S3DIS_test_mindspore.py --gpu 0 --test_area 5 --labeled_point 1 --log_dir '1pt-iteration10' --total_log '1pt'
